# generate this file from an existing pg_back.conf file: kubectl create secret generic backup-config --from-file=pg_back.conf --dry-run=client -oyaml -n postgres > secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backup-config
  namespace: postgres
data:
  pg_back.conf: <FILE AS STRING>
